version: "3.8"

services:
  execution:
    build: ./eth1
    entrypoint: ./nimbus_execution_client
    command: >
      --data-dir=/data
      --engine-api
      --engine-api-address=0.0.0.0
      --engine-api-port=8551
      --http-address=0.0.0.0
      --http-port=8545
      --rpc
      --rpc-api=eth,debug
    ports:
      - "8545:8545"
      - "30303:30303"
    volumes:
      - ./data/execution:/data

  consensus:
    build: ./eth2
    entrypoint: /entrypoint.sh
    command: >
      --data-dir=/data
      --el=http://execution:8551
      --el-jwt-secret=/execution-data/jwtsecret
    ports:
      - "9000:9000"
      - "5052:5052"
    volumes:
      - ./data/consensus:/data
      - ./data/execution:/execution-data
      - ./eth2/entrypoint.sh:/entrypoint.sh

  sync:
    build: ./eth1
    entrypoint: /bin/bash
    command: -c "while true; do ./nrpc sync --beacon-api=http://consensus:5052 --el-engine-api=http://execution:8551 --jwt-secret=/execution-data/jwt.hex; sleep 2; done"
    depends_on:
      - execution
      - consensus
    volumes:
      - ./data/execution:/execution-data
