version: "3.8"

services:
  execution:
    build: ./eth1
    entrypoint: ./nimbus_execution_client
    command: >
      --data-dir=/data
      --engine-api
      --engine-api-address=0.0.0.0
      --engine-api-port=8551
      --http-address=0.0.0.0
      --http-port=8545
      --rpc
      --rpc-api=eth,debug
    ports:
      - "8545:8545"
      - "30303:30303"
    volumes:
      - ./data/execution:/data

  consensus:
    build: ./eth2
    entrypoint: /entrypoint.sh
    command: >
      --data-dir=/data
      --web3-url=http://execution:8551
      --jwt-secret=/execution-data/jwt.hex
      --trusted-block-root=${TRUSTED_BLOCK_ROOT}
    ports:
      - "9000:9000"
      - "5052:5052"
    volumes:
      - ./data/consensus:/data
      - ./data/execution:/execution-data
      - ./eth2/entrypoint.sh:/entrypoint.sh
